os: linux

language: python

python:
  - "3.6"

# Safelist
branches:
  only:
    - master
    - develop

cache:
  npm: false
  pip: false

jobs:
  include:
    before_install:
      - pip --version
      - pip install mkdocs
      - pip install mkdocs-material
      - nvm install 8.13.0
      - npm install firebase-tools -g
      - npm install firebase-functions

    before_script:
      - make install-depencencies

    script:
      - make lint-functions
      - npm run build
      - make lint-storelocatorjs
      - npm run build:mkdocs:only
      - npm run create:demo

    deploy:
      - provider: firebase
        token: $FIREBASE_TOKEN
        cleanup: false
        project: storelocatorjs
        on:
          branch: develop
      - provider: pages
        local_dir: site
        cleanup: false
        token: $GITHUB_TOKEN
        keep_history: false
        edge: true
        commit_message: Deploy Travis CI to %{target_branch} branch
        on:
          branch: develop
